### ISSUE TITLE
OC not showing nothing

### ISSUE THREAD

**Issue by mauromarzocca** [vanyasem/hackintosh-xiaomi-air-7200U#1]
Hi, after I select the USB Drive, OpenCore showing a black screen. I cannot select any OS.

**Comment by vanyasem** [comment]
If you expect to get any sort of help or support, you should include as much information as possible
1) What is your laptop's exact model?
2) What is your BIOS version?
3) Have you patched CFG Lock in BIOS?
4) What is the operating system installed on your computer currently, if any?
5) What version of macOS are you trying to install?
6) How have you created the USB Drive?
7) What filesystem is used - APFS or HFS+?

**Comment by mauromarzocca** [comment]
1. My Model is Xiaomi Laptop 2017 i5-7200
2. The BIOS version is XMAKB3M0P1A12
3. Yes
4. Windows 10 + Ubuntu (i want to install MacOS on the second SSD)
5. I tried Sonoma and Ventura
6. Using MacOS Terminal (on a MacMini M1)
7. I cannot select a filesystem, when I select the USB to Boot I have a Black Screen

**Comment by vanyasem** [comment]
@mauromarzocca thanks for the info!
Do you have a completely black screen, or an OpenCore screen with no available boot entires?
Try pressing the Space Bar when you are on the "black screen", does anything change?
Attach a photo if possible

In any case, by default booting from external USB media is disabled by a scan policy
You will have to change `ScanPolicy`'s value to `0` in order to enable USB detection: https://github.com/vanyasem/hackintosh-xiaomi-air-7200U/blob/main/EFI/OC/config.plist#L1484

**Comment by vanyasem** [comment]
@mauromarzocca also, have you configured the serial number in the config [as per the documentation](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#using-gensmbios)?

**Comment by mauromarzocca** [comment]
@vanyasem I tried these method, but I haven't result.

**Comment by vanyasem** [comment]
@mauromarzocca please answer all of my questions in detail. I cannot help you any further unless you answer my questions.

**Comment by mauromarzocca** [comment]
I tried all your method, but the monitor is still black

**Comment by vanyasem** [comment]
@mauromarzocca 

If you expect to get any sort of help or support, you should pay attention to what is being asked, and provide detailed answers. I will repeat my questions that were left unanswered

1) Do you have a completely black screen, or an OpenCore screen with no available boot entires?
2) Try pressing the Space Bar when you are on the "black screen", does anything change?
3) Attach a photo of your black screen

**Comment by vanyasem** [comment]
@mauromarzocca still waiting for more info from you

**Comment by vanyasem** [comment]
@mauromarzocca I will be closing the issue on April 1st unless you provide me with the requested info

**Comment by mauromarzocca** [comment]
Hi, sorry for the delay, I should resolve this by changing the SSD and resetting the NVRAM

**Comment by vanyasem** [comment]
@mauromarzocca great! Glad to hear it worked. I hope you enjoy my EFI. Don't forget to check for updates from time to time, I am planning to continue supporting this repository for new macOS/OpenCore releases
